version: "3"
services:
  db-passport:
    platform: linux/amd64
    image: postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"

  web:
    platform: linux/amd64
    env_file:
      - ".env"
    build: .
    image: openskiessh/flight-passport
    command: ./entrypoint.sh
    ports:
      - "9000:9000"
    depends_on:
      - db-passport
    volumes:
      - .:/app

volumes:
  app:
  db_data:
