name: Publish openskies flight passport images to github packages
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags:
      - v*
env:
  IMAGE_NAME: ghcr.io/tiiuae/flight_passport
jobs:
  build-docker-image:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/tiiuae/flight_passport
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha
          type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          type=raw,value={{branch}}-{{date 'YYYYMMDD-HHmmss'}}-{{sha}},enable=${{ github.event_name != 'pull_request' && !startsWith(github.ref, 'refs/tags/v')}}
    - name: Print github.ref
      run: echo ${{ github.ref }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Create release
      uses: tiiuae/create-release-action@main
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        image-ref: ${{ env.IMAGE_NAME }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
